apiVersion: team.github.m.upbound.io/v1alpha1
kind: Members
metadata:
  annotations:
    meta.upbound.io/example-id: team/v1alpha1/members
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    members:
    - role: maintainer
      username: SomeUser
    - role: member
      username: AnotherUser
    teamSlugSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: team.github.m.upbound.io/v1alpha1
kind: Team
metadata:
  annotations:
    meta.upbound.io/example-id: team/v1alpha1/members
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    name: my-team
