apiVersion: team.github.upbound.io/v1alpha1
kind: TeamMembership
metadata:
  annotations:
    meta.upbound.io/example-id: team/v1alpha1/teammembership
  labels:
    testing.upbound.io/example-name: some_team_membership
  name: some-team-membership
spec:
  forProvider:
    role: member
    teamIdSelector:
      matchLabels:
        testing.upbound.io/example-name: some_team
    username: SomeUser

---

apiVersion: team.github.upbound.io/v1alpha1
kind: Team
metadata:
  annotations:
    meta.upbound.io/example-id: team/v1alpha1/teammembership
  labels:
    testing.upbound.io/example-name: some_team
  name: some-team
spec:
  forProvider:
    description: Some cool team
    name: SomeTeam
