apiVersion: actions.github.m.upbound.io/v1alpha1
kind: RepositoryPermissions
metadata:
  annotations:
    meta.upbound.io/example-id: actions/v1alpha1/repositorypermissions
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: upbound-system
spec:
  forProvider:
    allowedActions: selected
    allowedActionsConfig:
    - githubOwnedAllowed: true
      patternsAllowed:
      - actions/cache@*
      - actions/checkout@*
      verifiedAllowed: true
    repositorySelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: repo.github.m.upbound.io/v1alpha1
kind: Repository
metadata:
  annotations:
    meta.upbound.io/example-id: actions/v1alpha1/repositorypermissions
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    name: my-repository
