apiVersion: user.github.upbound.io/v1alpha1
kind: Membership
metadata:
  annotations:
    meta.upbound.io/example-id: user/v1alpha1/membership
  labels:
    testing.upbound.io/example-name: membership_for_some_user
  name: membership-for-some-user
spec:
  forProvider:
    role: member
    username: SomeUser
