apiVersion: repo.github.m.upbound.io/v1alpha1
kind: RepositoryCustomProperty
metadata:
  annotations:
    meta.upbound.io/example-id: repo/v1alpha1/repositorycustomproperty
  labels:
    testing.upbound.io/example-name: string
  name: string
  namespace: upbound-system
spec:
  forProvider:
    propertyName: my-cool-property
    propertyType: string
    propertyValue:
    - test
    repositorySelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: repo.github.m.upbound.io/v1alpha1
kind: Repository
metadata:
  annotations:
    meta.upbound.io/example-id: repo/v1alpha1/repositorycustomproperty
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    description: My awesome codebase
    name: example
