apiVersion: repo.github.upbound.io/v1alpha1
kind: PullRequest
metadata:
  annotations:
    meta.upbound.io/example-id: repo/v1alpha1/pullrequest
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    baseRef: main
    baseRepositorySelector:
      matchLabels:
        testing.upbound.io/example-name: example
    body: This will change everything
    headRefSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    title: My newest feature
