apiVersion: repo.github.upbound.io/v1alpha1
kind: RepositoryRuleset
metadata:
  annotations:
    meta.upbound.io/example-id: repo/v1alpha1/repositoryruleset
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    bypassActors:
    - actorId: 13473
      actorType: Integration
      bypassMode: always
    conditions:
    - refName:
      - exclude: []
        include:
        - ~ALL
    enforcement: active
    name: example
    repositorySelector:
      matchLabels:
        testing.upbound.io/example-name: example
    rules:
    - creation: true
      deletion: true
      requiredDeployments:
      - requiredDeploymentEnvironments:
        - test
      requiredLinearHistory: true
      requiredSignatures: true
      update: true
    target: branch

---

apiVersion: repo.github.upbound.io/v1alpha1
kind: Repository
metadata:
  annotations:
    meta.upbound.io/example-id: repo/v1alpha1/repositoryruleset
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Example repository
    name: example
