apiVersion: repo.github.upbound.io/v1alpha1
kind: TagProtection
metadata:
  annotations:
    meta.upbound.io/example-id: repo/v1alpha1/tagprotection
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    pattern: v*
    repositorySelector:
      matchLabels:
        testing.upbound.io/example-name: example
