name: hashicorp/null
resources:
    null_resource:
        subCategory: ""
        description: The null_resource resource implements the standard resource lifecycle but takes no further action. On Terraform 1.4 and later, use the terraform_data resource type https://developer.hashicorp.com/terraform/language/resources/terraform-data instead. The triggers argument allows specifying an arbitrary set of values that, when changed, will cause the resource to be replaced.
        name: null_resource
        title: null_resource Resource - terraform-provider-null
        examples:
            - name: cluster
              manifest: |-
                {
                  "connection": [
                    {
                      "host": "${element(aws_instance.cluster[*].public_ip, 0)}"
                    }
                  ],
                  "provisioner": {
                    "remote-exec": [
                      {
                        "inline": [
                          "bootstrap-cluster.sh ${join(\" \",\n      aws_instance.cluster[*].private_ip)}"
                        ]
                      }
                    ]
                  },
                  "triggers": {
                    "cluster_instance_ids": "${join(\",\", aws_instance.cluster[*].id)}"
                  }
                }
              dependencies:
                aws_instance.cluster: |-
                    {
                      "ami": "ami-0dcc1e21636832c5d",
                      "count": 3,
                      "instance_type": "m5.large"
                    }
        argumentDocs:
            id: (String) This is set to a random value at create time.
            triggers: (Map of String) A map of arbitrary strings that, when changed, will force the null resource to be replaced, re-running any associated provisioners.
        importStatements: []
