apiVersion: actions.github.upbound.io/v1alpha1
kind: OrganizationActionsSecret
metadata:
  name: organization-secret-test
spec:
  forProvider:
    secretName: TEST_SECRET
    visibility: private
    plaintextValueSecretRef:
      key: howdy
      name: organization-secret-secret 
      namespace: default
  providerConfigRef:
    name: default
---
apiVersion: v1 
kind: Secret 
metadata:
  name: organization-secret-secret 
stringData:
  howdy: a-secret-text
