apiVersion: actions.github.upbound.io/v1alpha1
kind: EnvironmentSecret
metadata:
  annotations:
    meta.upbound.io/example-id: actions/v1alpha1/environmentsecret
  labels:
    testing.upbound.io/example-name: example_plaintext
  name: example-plaintext
spec:
  forProvider:
    environmentSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    plaintextValueSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    repositorySelector:
      matchLabels:
        testing.upbound.io/example-name: example
    secretName: example_secret_name
