/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type OrganizationInitParameters struct {

	// List of organization owner usernames.
	// List of organization owner usernames.
	// +listType=set
	AdminLogins []*string `json:"adminLogins,omitempty" tf:"admin_logins,omitempty"`

	// The billing email address.
	// The billing email address.
	BillingEmail *string `json:"billingEmail,omitempty" tf:"billing_email,omitempty"`

	// The description of the organization.
	// The description of the organization.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The display name of the organization.
	// The display name of the organization.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The ID of the enterprise.
	// The ID of the enterprise.
	EnterpriseID *string `json:"enterpriseId,omitempty" tf:"enterprise_id,omitempty"`

	// The name of the organization.
	// The name of the organization.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type OrganizationObservation struct {

	// List of organization owner usernames.
	// List of organization owner usernames.
	// +listType=set
	AdminLogins []*string `json:"adminLogins,omitempty" tf:"admin_logins,omitempty"`

	// The billing email address.
	// The billing email address.
	BillingEmail *string `json:"billingEmail,omitempty" tf:"billing_email,omitempty"`

	// The ID of the organization.
	// The database ID of the organization.
	DatabaseID *int64 `json:"databaseId,omitempty" tf:"database_id,omitempty"`

	// The description of the organization.
	// The description of the organization.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The display name of the organization.
	// The display name of the organization.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The ID of the enterprise.
	// The ID of the enterprise.
	EnterpriseID *string `json:"enterpriseId,omitempty" tf:"enterprise_id,omitempty"`

	// The node ID of the organization for use with the v4 API.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The name of the organization.
	// The name of the organization.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type OrganizationParameters struct {

	// List of organization owner usernames.
	// List of organization owner usernames.
	// +kubebuilder:validation:Optional
	// +listType=set
	AdminLogins []*string `json:"adminLogins,omitempty" tf:"admin_logins,omitempty"`

	// The billing email address.
	// The billing email address.
	// +kubebuilder:validation:Optional
	BillingEmail *string `json:"billingEmail,omitempty" tf:"billing_email,omitempty"`

	// The description of the organization.
	// The description of the organization.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The display name of the organization.
	// The display name of the organization.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The ID of the enterprise.
	// The ID of the enterprise.
	// +kubebuilder:validation:Optional
	EnterpriseID *string `json:"enterpriseId,omitempty" tf:"enterprise_id,omitempty"`

	// The name of the organization.
	// The name of the organization.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// OrganizationSpec defines the desired state of Organization
type OrganizationSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     OrganizationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider OrganizationInitParameters `json:"initProvider,omitempty"`
}

// OrganizationStatus defines the observed state of Organization.
type OrganizationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        OrganizationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Organization is the Schema for the Organizations API. Create and manages a GitHub enterprise organization.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,github}
type Organization struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.adminLogins) || (has(self.initProvider) && has(self.initProvider.adminLogins))",message="spec.forProvider.adminLogins is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.billingEmail) || (has(self.initProvider) && has(self.initProvider.billingEmail))",message="spec.forProvider.billingEmail is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.enterpriseId) || (has(self.initProvider) && has(self.initProvider.enterpriseId))",message="spec.forProvider.enterpriseId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   OrganizationSpec   `json:"spec"`
	Status OrganizationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OrganizationList contains a list of Organizations
type OrganizationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Organization `json:"items"`
}

// Repository type metadata.
var (
	Organization_Kind             = "Organization"
	Organization_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Organization_Kind}.String()
	Organization_KindAPIVersion   = Organization_Kind + "." + CRDGroupVersion.String()
	Organization_GroupVersionKind = CRDGroupVersion.WithKind(Organization_Kind)
)

func init() {
	SchemeBuilder.Register(&Organization{}, &OrganizationList{})
}
