// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type DefaultBranchInitParameters struct {

	// (String) The name of the branch to set as the default (e.g. 'main').
	// The name of the branch to set as the default (e.g. 'main').
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-github/apis/namespaced/repo/v1alpha1.Branch
	Branch *string `json:"branch,omitempty" tf:"branch,omitempty"`

	// Reference to a Branch in repo to populate branch.
	// +kubebuilder:validation:Optional
	BranchRef *v1.NamespacedReference `json:"branchRef,omitempty" tf:"-"`

	// Selector for a Branch in repo to populate branch.
	// +kubebuilder:validation:Optional
	BranchSelector *v1.NamespacedSelector `json:"branchSelector,omitempty" tf:"-"`

	// (String) The ETag header for the repository API response.
	// The ETag header for the repository API response.
	Etag *string `json:"etag,omitempty" tf:"etag,omitempty"`

	// (Boolean) If true rename the existing branch when the branch input is changed. Defaults to 'false'.
	// If `true` rename the existing branch when the `branch` input is changed. Defaults to 'false'.
	Rename *bool `json:"rename,omitempty" tf:"rename,omitempty"`

	// (Boolean) If true, poll until GitHub propagates the renamed default branch before proceeding. Only has effect when rename is also true. Defaults to 'false'.
	// If `true`, poll until GitHub propagates the renamed default branch before proceeding. Only has effect when `rename` is also `true`. Defaults to 'false'.
	WaitForRename *bool `json:"waitForRename,omitempty" tf:"wait_for_rename,omitempty"`
}

type DefaultBranchObservation struct {

	// (String) The name of the branch to set as the default (e.g. 'main').
	// The name of the branch to set as the default (e.g. 'main').
	Branch *string `json:"branch,omitempty" tf:"branch,omitempty"`

	// (String) The ETag header for the repository API response.
	// The ETag header for the repository API response.
	Etag *string `json:"etag,omitempty" tf:"etag,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) If true rename the existing branch when the branch input is changed. Defaults to 'false'.
	// If `true` rename the existing branch when the `branch` input is changed. Defaults to 'false'.
	Rename *bool `json:"rename,omitempty" tf:"rename,omitempty"`

	// (Number) The ID of the GitHub repository.
	// The ID of the GitHub repository.
	RepositoryID *int64 `json:"repositoryId,omitempty" tf:"repository_id,omitempty"`

	// (Boolean) If true, poll until GitHub propagates the renamed default branch before proceeding. Only has effect when rename is also true. Defaults to 'false'.
	// If `true`, poll until GitHub propagates the renamed default branch before proceeding. Only has effect when `rename` is also `true`. Defaults to 'false'.
	WaitForRename *bool `json:"waitForRename,omitempty" tf:"wait_for_rename,omitempty"`
}

type DefaultBranchParameters struct {

	// (String) The name of the branch to set as the default (e.g. 'main').
	// The name of the branch to set as the default (e.g. 'main').
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-github/apis/namespaced/repo/v1alpha1.Branch
	// +kubebuilder:validation:Optional
	Branch *string `json:"branch,omitempty" tf:"branch,omitempty"`

	// Reference to a Branch in repo to populate branch.
	// +kubebuilder:validation:Optional
	BranchRef *v1.NamespacedReference `json:"branchRef,omitempty" tf:"-"`

	// Selector for a Branch in repo to populate branch.
	// +kubebuilder:validation:Optional
	BranchSelector *v1.NamespacedSelector `json:"branchSelector,omitempty" tf:"-"`

	// (String) The ETag header for the repository API response.
	// The ETag header for the repository API response.
	// +kubebuilder:validation:Optional
	Etag *string `json:"etag,omitempty" tf:"etag,omitempty"`

	// (Boolean) If true rename the existing branch when the branch input is changed. Defaults to 'false'.
	// If `true` rename the existing branch when the `branch` input is changed. Defaults to 'false'.
	// +kubebuilder:validation:Optional
	Rename *bool `json:"rename,omitempty" tf:"rename,omitempty"`

	// (Boolean) If true, poll until GitHub propagates the renamed default branch before proceeding. Only has effect when rename is also true. Defaults to 'false'.
	// If `true`, poll until GitHub propagates the renamed default branch before proceeding. Only has effect when `rename` is also `true`. Defaults to 'false'.
	// +kubebuilder:validation:Optional
	WaitForRename *bool `json:"waitForRename,omitempty" tf:"wait_for_rename,omitempty"`
}

// DefaultBranchSpec defines the desired state of DefaultBranch
type DefaultBranchSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            DefaultBranchParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DefaultBranchInitParameters `json:"initProvider,omitempty"`
}

// DefaultBranchStatus defines the observed state of DefaultBranch.
type DefaultBranchStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DefaultBranchObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DefaultBranch is the Schema for the DefaultBranchs API. Configures the default branch for a GitHub repository.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,github}
type DefaultBranch struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              DefaultBranchSpec   `json:"spec"`
	Status            DefaultBranchStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DefaultBranchList contains a list of DefaultBranchs
type DefaultBranchList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DefaultBranch `json:"items"`
}

// Repository type metadata.
var (
	DefaultBranch_Kind             = "DefaultBranch"
	DefaultBranch_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DefaultBranch_Kind}.String()
	DefaultBranch_KindAPIVersion   = DefaultBranch_Kind + "." + CRDGroupVersion.String()
	DefaultBranch_GroupVersionKind = CRDGroupVersion.WithKind(DefaultBranch_Kind)
)

func init() {
	SchemeBuilder.Register(&DefaultBranch{}, &DefaultBranchList{})
}
