/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type BranchInitParameters struct {

	// The repository branch to create.
	// The repository branch to create.
	Branch *string `json:"branch,omitempty" tf:"branch,omitempty"`

	// The GitHub repository name.
	// The GitHub repository name.
	// +crossplane:generate:reference:type=github.com/coopnorge/provider-github/apis/repo/v1alpha1.Repository
	Repository *string `json:"repository,omitempty" tf:"repository,omitempty"`

	// Reference to a Repository in repo to populate repository.
	// +kubebuilder:validation:Optional
	RepositoryRef *v1.Reference `json:"repositoryRef,omitempty" tf:"-"`

	// Selector for a Repository in repo to populate repository.
	// +kubebuilder:validation:Optional
	RepositorySelector *v1.Selector `json:"repositorySelector,omitempty" tf:"-"`

	// The branch name to start from. Defaults to main.
	// The branch name to start from. Defaults to 'main'.
	SourceBranch *string `json:"sourceBranch,omitempty" tf:"source_branch,omitempty"`

	// The commit hash to start from. Defaults to the tip of source_branch. If provided, source_branch is ignored.
	// The commit hash to start from. Defaults to the tip of 'source_branch'. If provided, 'source_branch' is ignored.
	SourceSha *string `json:"sourceSha,omitempty" tf:"source_sha,omitempty"`
}

type BranchObservation struct {

	// The repository branch to create.
	// The repository branch to create.
	Branch *string `json:"branch,omitempty" tf:"branch,omitempty"`

	// An etag representing the Branch object.
	// An etag representing the Branch object.
	Etag *string `json:"etag,omitempty" tf:"etag,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A string representing a branch reference, in the form of refs/heads/<branch>.
	// A string representing a branch reference, in the form of 'refs/heads/<branch>'.
	Ref *string `json:"ref,omitempty" tf:"ref,omitempty"`

	// The GitHub repository name.
	// The GitHub repository name.
	Repository *string `json:"repository,omitempty" tf:"repository,omitempty"`

	// A string storing the reference's HEAD commit's SHA1.
	// A string storing the reference's HEAD commit's SHA1.
	Sha *string `json:"sha,omitempty" tf:"sha,omitempty"`

	// The branch name to start from. Defaults to main.
	// The branch name to start from. Defaults to 'main'.
	SourceBranch *string `json:"sourceBranch,omitempty" tf:"source_branch,omitempty"`

	// The commit hash to start from. Defaults to the tip of source_branch. If provided, source_branch is ignored.
	// The commit hash to start from. Defaults to the tip of 'source_branch'. If provided, 'source_branch' is ignored.
	SourceSha *string `json:"sourceSha,omitempty" tf:"source_sha,omitempty"`
}

type BranchParameters struct {

	// The repository branch to create.
	// The repository branch to create.
	// +kubebuilder:validation:Optional
	Branch *string `json:"branch,omitempty" tf:"branch,omitempty"`

	// The GitHub repository name.
	// The GitHub repository name.
	// +crossplane:generate:reference:type=github.com/coopnorge/provider-github/apis/repo/v1alpha1.Repository
	// +kubebuilder:validation:Optional
	Repository *string `json:"repository,omitempty" tf:"repository,omitempty"`

	// Reference to a Repository in repo to populate repository.
	// +kubebuilder:validation:Optional
	RepositoryRef *v1.Reference `json:"repositoryRef,omitempty" tf:"-"`

	// Selector for a Repository in repo to populate repository.
	// +kubebuilder:validation:Optional
	RepositorySelector *v1.Selector `json:"repositorySelector,omitempty" tf:"-"`

	// The branch name to start from. Defaults to main.
	// The branch name to start from. Defaults to 'main'.
	// +kubebuilder:validation:Optional
	SourceBranch *string `json:"sourceBranch,omitempty" tf:"source_branch,omitempty"`

	// The commit hash to start from. Defaults to the tip of source_branch. If provided, source_branch is ignored.
	// The commit hash to start from. Defaults to the tip of 'source_branch'. If provided, 'source_branch' is ignored.
	// +kubebuilder:validation:Optional
	SourceSha *string `json:"sourceSha,omitempty" tf:"source_sha,omitempty"`
}

// BranchSpec defines the desired state of Branch
type BranchSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     BranchParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider BranchInitParameters `json:"initProvider,omitempty"`
}

// BranchStatus defines the observed state of Branch.
type BranchStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        BranchObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Branch is the Schema for the Branchs API. Creates and manages branches within GitHub repositories.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,github}
type Branch struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.branch) || (has(self.initProvider) && has(self.initProvider.branch))",message="spec.forProvider.branch is a required parameter"
	Spec   BranchSpec   `json:"spec"`
	Status BranchStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BranchList contains a list of Branchs
type BranchList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Branch `json:"items"`
}

// Repository type metadata.
var (
	Branch_Kind             = "Branch"
	Branch_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Branch_Kind}.String()
	Branch_KindAPIVersion   = Branch_Kind + "." + CRDGroupVersion.String()
	Branch_GroupVersionKind = CRDGroupVersion.WithKind(Branch_Kind)
)

func init() {
	SchemeBuilder.Register(&Branch{}, &BranchList{})
}
