name: Publish Provider Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version string to use while publishing the package (e.g. v1.0.0-alpha.1)"
        default: ""
        required: false
      go-version:
        description: "Go version to use if building needs to be done"
        default: "1.24"
        required: false
      registry-org:
        description: "Organization to publish the package to (e.g. crossplane-contrib)"
        default: "crossplane-contrib"
        required: false

jobs:
  publish-provider-package:
    permissions:
      contents: read
      packages: write
    uses: crossplane-contrib/provider-workflows/.github/workflows/publish-provider.yml@451c4dc6ad3691b0a702a997a0ac24e8bbc8bbaa # v0.19.0
    with:
      repository: provider-upjet-github
      registry_org: ${{ github.event.inputs.registry-org }}
      version: ${{ github.event.inputs.version }}
      go-version: ${{ github.event.inputs.go-version }}
      cleanup-disk: true
      mirror: false
    secrets:
      GHCR_PAT: ${{ secrets.GITHUB_TOKEN }}
